# Generated by Django 3.2.16 on 2022-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purria_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
