# Generated by Django 3.2.16 on 2022-11-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purria_backend', '0002_auto_20221112_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='name',
            new_name='garden_contract_id',
        ),
    ]
