# Generated by Django 3.2.16 on 2022-11-12 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purria_backend', '0004_alter_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='gardens_count',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
